### ISSUE TITLE
how fix this

### ISSUE THREAD

**Issue by Kalimon12** [VainlyStrain/Vailyn#17]
root@kali:~/Vailyn# python3 Vailyn -h
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.Notifications': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Vailyn/Vailyn", line 113, in <module>
    notify2.init("Vailyn")
  File "/usr/local/lib/python3.9/dist-packages/notify2.py", line 102, in init
    dbus_obj = bus.get_object('org.freedesktop.Notifications',
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files

**Comment by VainlyStrain** [comment]
Are you running Vailyn on a machine with a graphical interface? This is an intern error of notify2, which is a library to display graphical notifications.

If you have a GUI installed, then I don't know what might be causing this. A quick way to fix this would be to modify the core/config.py file, and set DESKTOP_NOTIFY to False. This will disable the notification feature entirely, and should thus resolve the issue.

Greetings!

**Comment by VainlyStrain** [comment]
Closing this, since it is not related to Vailyn directly, and the proposed fix should work. If the problem remains, feel free to open this issue again.

**Comment by VainlyStrain** [comment]
Hi!

I've added a CLI argument `--notmain`, that should prevent this error.

Greetings!
